theme = "george" 

[editor]
line-number = "relative"
bufferline = "multiple" 
text-width = 100
rulers = [100]

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"] 
center = ["diagnostics"]
right = ["position-percentage", "file-type", "separator", "file-line-ending"]
[editor.whitespace]
render = "all"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⤶"
space = "·"
tab = "→"

[editor.indent-guides]
render = true 
character = "⸽"  # Some characters that work well: "▏", "┆", "┊", "⸽" 
skip-levels = 1 

[editor.soft-wrap]
enable = true 

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.insert]
up = "no_op" 
down = "no_op" 
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op" 

[keys.select]
X = ["select_line_above"]
x = ["select_line_below"]
C-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
C-j = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]

[keys.normal]
X = ["select_line_above"]
x = ["select_line_below"]
ret = "command_mode"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.space]
t = ":sh zellij run -ci --name gitui -- gitui"
z = ":sh export EDITOR=hx; zellij run -ci --name yazi -- yazi $(pwd)"
F = { a = ":toggle file-picker.hidden", F = "file_picker_in_current_directory"}
