theme = "tokyonight" 

[editor]
line-number = "relative"
bufferline = "multiple" 
text-width = 100
rulers = [100]

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"] 

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true 
character = "⸽"  # Some characters that work well: "▏", "┆", "┊", "⸽" 
skip-levels = 1 

[editor.soft-wrap]
enable = true 

[keys.insert]
up = "no_op" 
down = "no_op" 
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op" 

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
C-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
C-j = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
ret = "command_mode"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
